stages:
- stage: setup
  jobs:
  - job: windows_setup
    pool:
      vmImage: 'windows-2025'
    timeoutInMinutes: 9999
    steps:

    # Install ngrok via WinGet
    - powershell: |
        Write-Host "Installing ngrok using WinGet..."
        winget install --id Ngrok.Ngrok --accept-package-agreements --accept-source-agreements
        ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
      displayName: 'Install and configure ngrok (WinGet)'

    - powershell: |
        # Configure Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
      displayName: 'Configure Remote Desktop'

    - powershell: |
        # Create User runneradmin
        echo "Checking if user 'runneradmin' exists..."
        $existingUser = Get-LocalUser -Name 'runneradmin' -ErrorAction SilentlyContinue
        if (-not $existingUser) {
            New-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString $env:ADMIN_PASSWORD -AsPlainText -Force) -PasswordNeverExpires:$true -AccountNeverExpires:$true
            Add-LocalGroupMember -Group 'Administrators' -Member 'runneradmin'
        }
      displayName: 'Create User runneradmin'

    - powershell: |
        ngrok tcp 3389
      displayName: 'Run ngrok for RDP'
