stages:
- stage: setup
  jobs:
  - job: windows_setup
    pool:
      vmImage: 'windows-2025'
    timeoutInMinutes: 9999
    steps:

    # Scoop install (ExecutionPolicy-safe)
    - powershell: |
        Write-Host "Installing Scoop (execution-policy-safe mode)..."

        if (-not (Get-Command scoop.exe -ErrorAction SilentlyContinue)) {
            iwr -useb get.scoop.sh | iex
        }

        scoop bucket add main
        scoop bucket add extras

        scoop install ngrok

        ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
      displayName: 'Install ngrok using Scoop'

    - powershell: |
        # Configure Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
      displayName: 'Configure Remote Desktop'

    - powershell: |
        # Create User runneradmin
        echo "Checking if user 'runneradmin' exists before creating..."
        $existingUser = Get-LocalUser -Name 'runneradmin' -ErrorAction SilentlyContinue
        if ($existingUser) {
            echo "User 'runneradmin' already exists."
        } else {
            echo "User 'runneradmin' does not exist or an error occurred."
            $userCreationOutput = New-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString $env:ADMIN_PASSWORD -AsPlainText -Force) -PasswordNeverExpires:$true -AccountNeverExpires:$true -ErrorAction Stop
            if ($userCreationOutput) {
                echo "User 'runneradmin' created successfully."
                Add-LocalGroupMember -Group 'Administrators' -Member 'runneradmin' -ErrorAction Stop
            } else {
                echo "Error creating user 'runneradmin': $userCreationOutput"
                exit 1
            }
        }
      displayName: 'Create User runneradmin'

    - powershell: |
        ngrok tcp 3389
      displayName: 'Run ngrok for RDP'
